---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart isc-dhcp-server
  service:
    name: '{{ item.value }}'
    state: 'restarted'
  when: item.key in isc_dhcpd_protocols
  with_dict:
    'DHCPv4': 'dhcpd'
    'DHCPv6': 'dhcpd6'
