---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Commit UCI changes
  ganto.openwrt.uci:
    commit: true
  when: network_uci_commit | bool
  register: network_register_uci_commit
