---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Commit UCI resolver changes
  ganto.openwrt.uci:
    commit: true
    config: resolver
  when: resolver_uci_commit | bool
  register: resolver_register_uci_commit
