---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Check for uncommitted UCI network changes
  check_mode: no
  changed_when: false
  ganto.openwrt.uci:
    command: changes
    config: network
  register: network_register_uncommitted

- name: Abort on uncommitted UCI network changes
  fail:
    msg: 'Please review and commit UCI changes before continue'
  when: not network_register_uncommitted.result.committed
