---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: '{{ network_include_interface.key }} - Define network interface'
  ganto.openwrt.uci:
    command: set
    config: network
    section: '{{ network_include_interface.key }}'
    value: interface
  notify: 'Commit UCI network changes'

- name: '{{ network_include_interface.key }} - Set interface options'
  ganto.openwrt.uci:
    command: set
    config: network
    section: '{{ network_include_interface.key }}'
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: '{{ network_include_interface.value | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  notify: 'Commit UCI network changes'
