---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Repository metadata directory
  file:
    path: '{{ opkg_cfg_option_listsdir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Define opkg.conf
  template:
    src: opkg.conf.j2
    dest: /etc/opkg.conf
    owner: root
    group: root
    mode: '0644'

- name: Distribution repository feeds
  template:
    src: feeds.conf.j2
    dest: /etc/opkg/distfeeds.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    opkg_tmpl_feeds: '{{ opkg_dist_feeds }}'
  register: opkg_register_distfeeds

- name: Custom repository feeds
  template:
    src: feeds.conf.j2
    dest: /etc/opkg/customfeeds.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    opkg_tmpl_feeds: '{{ opkg_custom_feeds }}'
  register: opkg_register_customfeeds

- name: Update opkg feeds
  command: opkg update
  when: (opkg_register_distfeeds is changed
         or opkg_register_customfeeds is changed
         or opkg_update_feeds)

- name: Install packages
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ opkg_install_packages }}'

- name: Include tasks to update packages
  include_tasks: update.yml
  when: opkg_update_packages | bool
