---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Converge
  hosts: all

  vars:
    # Assigning a IPv6 ULA prefix is not supported in a container
    network_globals_default_config: {}

    # Test container only has one network interface
    network_interface_layout: single_dynamic

    # Disable IPv6 as it's not supported in a container
    network_interfaces:
      wan:
        ipv6: 0

  roles:
    - name: ganto.openwrt.opkg
    - name: ganto.openwrt.network
    - name: ganto.openwrt.system
