---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Update package metadata
      raw: opkg update  # noqa no-changed-when

    - name: Install Python 3
      raw: opkg install python3  # noqa no-changed-when

    - name: Disable dnsmasq capability check
      raw: sed -i 's/--user=dnsmasq/--user=root/' /etc/init.d/dnsmasq  # noqa no-changed-when
