---
#
# opkg - Package Manager Configuration
#
# For more information see `man(5) opkg.conf`.

# Dictionary of destination options defined in `/etc/opkg.conf`. Each item must
# correspond to the format: `<name>: <path>`.
opkg_cfg_option_dest:
  root: '/'
  ram: '/tmp'

# Dictionary of arch options defined in `/etc/opkg.conf`. Each item defines an
# architecture with a priority in the format `<arch>: <priority>`.
opkg_cfg_option_arch: {}

# Directory path used to store local copies of the repository information.
opkg_cfg_option_listsdir: '/var/opkg-lists'

# Dictionary of configuration options to be defined in `/etc/opkg.conf`. Each
# item must correspond to the format: `<option>: <value>`
opkg_cfg_options: '{{ opkg_default_cfg_options
                      | combine(opkg_custom_cfg_options) }}'

# Dictionary of default configuration options to be defined `/etc/opkg.conf`.
opkg_default_cfg_options:
  overlay_root: '/overlay'

  # Performs a signature check against the package index.
  check_signature: 1

# Dictionary of custom configuration options to be defined in `/etc/opkg.conf`.
opkg_custom_cfg_options: {}

# Configuration dictionary of distribution repository feeds to be defined in
# `/etc/opkg/distfeeds.conf`. The following dictinary keys must be defined:
#
#   base_url        Base URL prefix used to construct the feed URL
#   default_type    Default repository type used if not explicitly specified
#                   for the feed
#   feed            List of individual repository feeds
#
# Each repository feed item is another dictionary that can specify the
# following dictionary keys:
#
#   name    (required)    Name of the repository
#   path    (required)    URL path that will be added to the `base_url`
#   type    (optional)    Repository type (`src` or `src/gz`). Defaults to the
#                         `default_type`.
#
opkg_dist_feeds: '{{ opkg_default_dist_feeds[ansible_distribution | lower]
                     | combine(opkg_dist_feed_override) }}'

# Configuration dictionary that can be used to overwrite configuration keys
# defined in `opkg_default_dist_feeds`. If you define the `opkg_dist_feeds`
# variable yourself this can be ignored.
#
# However when using the default repositories this can be used to e.g.
# customize the release or set a local mirror URL. E.g.:
#
#   opkg_dist_feed_override:
#     base_url: http://downloads.openwrt.org/snapshots/
#
# For TurrisOS-based routers it can be used as alternative to `switch-branch`
# by setting the `base_url` to e.g. the HBT (Here Be Turtles) repository:
#
#   opkg_dist_feed_override:
#     base_url: https://repo.turris.cz/hbt/omnia/packages/
#
opkg_dist_feed_override: {}

# Dictionary of default repository definitions of varous OpenWRT distributions.
opkg_default_dist_feeds:
  # OpenWRT (https://openwrt.org/)
  openwrt:
    base_url: 'http://downloads.openwrt.org/releases/{{ ansible_distribution_version }}/'
    default_type: src/gz
    feeds:
      - name: openwrt_core
        path: 'targets/{{ ansible_architecture | regex_replace("_", "/") }}/packages'
      - name: openwrt_base
        path: 'packages/{{ ansible_architecture }}/base'
      - name: openwrt_freifunk
        path: 'packages/{{ ansible_architecture }}/freifunk'
      - name: openwrt_luci
        path: 'packages/{{ ansible_architecture }}/luci'
      - name: openwrt_packages
        path: 'packages/{{ ansible_architecture }}/packages'
      - name: openwrt_routing
        path: 'packages/{{ ansible_architecture }}/routing'
      - name: openwrt_telephony
        path: 'packages/{{ ansible_architecture }}/telephony'

  # TurrisOS (https://docs.turris.cz/)
  turrisos:
    base_url: 'https://repo.turris.cz/hbs/omnia/packages/'
    default_type: src/gz
    feeds:
      - name: turrisos_core
        path: core
      - name: turrisos_base
        path: base
      - name: turrisos_cesnet
        path: cesnet
      - name: turrisos_luci
        path: luci
      - name: turrisos_node
        path: node
      - name: turrisos_openwisp
        path: openwisp
      - name: turrisos_packages
        path: packages
      - name: turrisos_routing
        path: routing
      - name: turrisos_sidn
        path: sidn
      - name: turrisos_telephony
        path: telephony
      - name: turrisos_turrispackages
        path: turrispackages

# Configuration dictionary of custom repository feeds to be defined in
# `/etc/opkg/customfeeds.conf`. The format corresponds to `opkg_dist_feeds`.
opkg_custom_feeds: {}

# Always update repository feeds when running the role. By default the feeds
# are only updated if `opkg_update_packages: true` or if the feed configuration
# was changed.
opkg_update_feeds: '{{ true if opkg_update_packages|bool else false }}'

# Update all packages to the latest version when running the role.
opkg_update_packages: false

# Name of tool used for package updates. Accepts `opkg` (default for OpenWRT)
# or `pkgupdate` (default for TurrisOS).
opkg_update_tool: '{{ "pkgupdate" if (ansible_distribution == "TurrisOS")
                                  else "opkg" }}'

# List of custom arguments added to the `opkg` update command if
# `opkg_update_tool: opkg`.
opkg_update_opkg_args: []

# List of custom arguments added to the `pkgupdate` command if
# `opkg_update_tool: pkgupdate`.
opkg_update_pkgupdate_args: []

# Reboot host in case packages listed in `opkg_update_reboot_packages` were
# updated. Setting will be ignored if `opkg_update_packages: false`.
opkg_update_reboot: true

# List of package names that trigger a host reboot. Setting will be ignored
# if `opkg_update_packages` or `opkg_update_reboot` is set to `false`.
opkg_update_reboot_packages:
  - kernel

# Host name (or inventory name) of host to which the task for the SSH check
# after reboot is delegated to. Set this to a jump host if the target host is
# not directly reachable from the Ansible controller.
opkg_reboot_check_delegate_to: localhost
