---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Check for uncommitted UCI dhcp changes
  check_mode: no
  changed_when: false
  ganto.openwrt.uci:
    command: changes
    config: dhcp
  register: dnsmasq_register_dhcp_uncommitted

- name: Abort on uncommitted UCI dhcp changes
  fail:
    msg: 'Please review and commit UCI changes before continue'
  when:
    - not dnsmasq_register_dhcp_uncommitted.result.committed
    - dnsmasq_dhcp_abort_uncommitted | bool
