---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: '{{ dnsmasq_include_dhcp_host.duid
            | default(dnsmasq_include_dhcp_host.mac[0]) }} - Add DHCP host'
  ganto.openwrt.uci:
    command: add
    config: dhcp
    section: host
  when: (ansible_facts.uci.dhcp.host | default([])) | length <= dnsmasq_include_dhcp_host_index

- name: '{{ dnsmasq_include_dhcp_host.duid
            | default(dnsmasq_include_dhcp_host.mac[0]) }} - Set DHCP host attributes'
  ganto.openwrt.uci:
    command: set
    config: dhcp
    section: '@host[{{ dnsmasq_include_dhcp_host_index }}]'
    option: '{{ item.key }}'
    value: '{{ item.value | ganto.openwrt.uci_type }}'
  loop: '{{ dnsmasq_include_dhcp_host | dict2items }}'
  loop_control:
    label: '{{ (item.key + ": "
                + (item.value | ganto.openwrt.uci_type | string))
               | to_json }}'
  notify: 'Commit UCI dhcp changes'
