---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: '{{ dnsmasq_include_srv_record.srv }} - Add DNS SRV record'
  ganto.openwrt.uci:
    command: add
    config: dhcp
    section: srvhost
  when: (ansible_facts.uci.dhcp.srvhost | default([])) | length <= dnsmasq_include_srv_record_index

- name: '{{ dnsmasq_include_srv_record.srv }} - Set DNS SRV record attributes'
  ganto.openwrt.uci:
    command: set
    config: dhcp
    section: '@srvhost[{{ dnsmasq_include_srv_record_index }}]'
    option: '{{ item.key }}'
    value: '{{ item.value | ganto.openwrt.uci_type }}'
  when: item.key in ['srv', 'target', 'port', 'class', 'weight']
  loop: '{{ dnsmasq_include_srv_record | dict2items }}'
  loop_control:
    label: '{{ (item.key + ": "
                + (item.value | ganto.openwrt.uci_type | string))
               | to_json }}'
  notify: 'Commit UCI dhcp changes'
