---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Commit UCI system changes
  ganto.openwrt.uci:
    commit: true
  when: system_uci_commit | bool
  register: system_register_uci_commit
