---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
platforms:
  - name: instance
    image: "openwrtorg/rootfs:x86_64-19.07.6"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: True
provisioner:
  name: ansible
  log: True
  options:
    vvv: True
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
