---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

#
# Generic system configuration
#

# Host name
system_hostname: openwrt

# Timezone name of the system (e.g. 'Europe/London')
system_zonename: UTC

# YAML dictionary of UCI system options such as system logging level and remote
# log server as they will be applied to the host. For the full list of options
# see:
#   https://openwrt.org/docs/guide-user/base-system/system_configuration
#
system_options: '{{ system_default_options | combine(system_custom_options) }}'

# YAML dictionary of the UCI systems option defaults as defined by OpenWRT.
system_default_options:

  # Maximum log level for kernel messages to be logged to the console.
  conloglevel: 8

  # The minimum level for cron messages to be logged to syslog.
  cronloglevel: 5

  # Size of the file based log buffer in KiB.
  log_size: 64

  # Require authentication for local users to log in the system.
  ttylogin: false

# YAML dictionary of user defined UCI systems options which can be used to
# overwrite the default options.
system_custom_options: {}

#
# NTP client/server configuration
#
# By default OpenWRT will use the busybox-ntpd to either sync the time via NTP
# at startup when used as a client or run as daemon when to provide the NTP
# service via network. It can be replaced with an alternative NTP client or
# daemon (e.g. ISC ntpd) which must be configured seperatly. The default
# configuration of this role mostly corresponds to the default configuration
# of OpenWRT.

# Enable NTP time synchronization at startup.
system_ntp_enabled: true

# Use NTP servers provided via DHCP for time synchronization.
system_ntp_use_dhcp: true

# List of NTP servers used for for time synchronization if none provided via
# DHCP.
system_ntp_servers:
  - 0.openwrt.pool.ntp.org
  - 1.openwrt.pool.ntp.org
  - 2.openwrt.pool.ntp.org
  - 3.openwrt.pool.ntp.org

# Enable NTP daemon that can be queried by other network hosts.
system_ntp_daemon: false

#
# Generic role behavior
#

# Abort if there are uncommitted system changes before running this role.
system_abort_uncommitted: true

# Commit UCI system changes to persistency.
system_uci_commit: true

# Restart system service after changes.
system_service_restart: true
