---
#
# Generic system configuration
#

# Host name
system_hostname: openwrt

# Timezone of the system. Corresponds to the `zonename` UCI option.
system_timezone: UTC

# YAML dictionary that defines the UCI system options such as system logging
# level and remote log server. For the full list of options see:
#   https://openwrt.org/docs/guide-user/base-system/system_configuration
#
system_options: '{{ system_default_options | combine(system_custom_options) }}'

# YAML dictionary that defines the default UCI systems options.
system_default_options:
  conloglevel: 8
  cronloglevel: 5
  log_size: 64
  ttylogin: false

# YAML dictionary that defines the user defined UCI systems options.
system_custom_options: {}

#
# NTP client/server configuration
#
# By default OpenWRT will use the busybox-ntpd to either sync the time via NTP
# at startup when used as a client or run as daemon when to provide the NTP
# service via network. It can be replaced with an alternative NTP client or
# daemon (e.g. ISC ntpd) which must be configured seperatly. The default
# configuration of this role mostly corresponds to the default configuration
# of OpenWRT.

# Enable NTP time synchronization at startup.
system_ntp_enabled: true

# Use NTP servers provided via DHCP for time synchronization.
system_ntp_use_dhcp: true

# List of NTP servers used for for time synchronization if none provided via
# DHCP.
system_ntp_servers:
  - 0.openwrt.pool.ntp.org
  - 1.openwrt.pool.ntp.org
  - 2.openwrt.pool.ntp.org
  - 3.openwrt.pool.ntp.org

# Enable NTP daemon that can be queried by other network hosts.
system_ntp_daemon: false

#
# Generic role behavior
#

# Abort if there are uncommitted system changes before running this role.
system_abort_uncommitted: true

# Commit UCI system changes to persistency.
system_uci_commit: true
