---
# Copyright (C) 2021, Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  become: true
  collections:
    - ganto.openwrt

  roles:
    - name: opkg
      tags: openwrt.opkg

    - name: network
      tags: openwrt.network

    - name: dnsmasq
      tags: openwrt.dnsmasq

    - name: isc_dhcpd
      tags: openwrt.isc_dhcpd

    - name: system
      tags: openwrt.system
