---
# Copyright (C) 2021, Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  become: true
  collections:
    - ganto.openwrt

  tasks:
    - import_role:  # noqa unnamed-task
        name: opkg
      tags: openwrt.opkg

    - import_role:  # noqa unnamed-task
        name: network
      tags: openwrt.network

    - import_role:  # noqa unnamed-task
        name: dnsmasq
      tags: openwrt.dnsmasq

    - import_role:  # noqa unnamed-task
        name: system
      tags: openwrt.system

    - import_role:  # noqa unnamed-task
        name: resolver
      when: ansible_distribution == 'TurrisOS'
      tags: openwrt.resolver
