---

- hosts: all
  become: true
  collections:
    - ganto.openwrt

  roles:
    - name: opkg
      tags: openwrt.opkg

    - name: network
      tags: openwrt.network

    - name: system
      tags: openwrt.system
