---
# Copyright (C) 2021, Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  become: true
  collections:
    - ganto.openwrt

  vars:
    opkg_update_packages: true

  roles:
    - name: opkg
